implementation_sources = [
    {
        "state_id": "CA",
        "implementation_type": "Executive Order",
        "implementation_notes": "Establishes CA’s 30×30 conservation goal and directs implementation.",
        "implementation_citation": "State of California. (2020, October 7). Executive Order N-82-20.",
        "implementation_url": "https://www.gov.ca.gov/wp-content/uploads/2020/10/10.07.2020-EO-N-82-20-.pdf",
    },
    {
        "state_id": "CA",
        "implementation_type": "Statute",
        "implementation_notes": "Codifies 30×30 conservation goal in statute (chaptered 2023).",
        "implementation_citation": "California Legislature. (2023). Senate Bill 337 (Chapter 392, Statutes of 2023): Environmental protection: lands and coastal waters conservation goal. Approved October 7, 2023.",
        "implementation_url": "https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202320240SB337"
    },
    {
        "state_id": "HI",
        "implementation_type": "Executive Commitment",
        "implementation_notes": "DLNR marine 30×30 roadmap (program guidance; not a statute or executive order)",
        "implementation_citation": "Hawaiʻi Department of Land and Natural Resources, Division of Aquatic Resources. (2020, December). Holomua: Marine 30×30 — Roadmap to effective management of near-shore waters.",
        "implementation_url": "https://dlnr.hawaii.gov/dar/files/2020/12/HolomuaMarine30x30_Roadmap_final.pdf",
    },
    {
        "state_id": "IL",
        "implementation_type": "Statute (Other)",
        "implementation_notes": "Creates 30×30 task force; no binding statewide 30×30 mandate.",
        "implementation_citation": "State of Illinois. (2021, August 27). Public Act 102-0618: Illinois Thirty-by-Thirty Conservation Task Force Act.",
        "implementation_url": "https://www.ilga.gov/Legislation/publicacts/view/102-0618",
    },
    {
        "state_id": "IL",
        "implementation_type": "Legislative Resolution",
        "implementation_notes": "Senate Resolution 632 – Establishing a 30x30 Coordinating Council; non-binding legislative expression of support.",
        "implementation_citation": "Illinois General Assembly. (2024). Senate Resolution 632 – Establishing a 30x30 Coordinating Council [Resolution].",
        "implementation_url": "https://www.ilga.gov/Legislation/BillStatus?DocNum=632&GAID=17&DocTypeID=SR&LegId=151047&SessionID=112&GA=103",
    },
    {
        "state_id": "NV",
        "implementation_type": "Legislative Resolution",
        "implementation_notes": "AJR No. 3 (81st Leg., 2021); non-binding legislative expression of support.",
        "implementation_citation": "Nevada Legislature. (2021). Assembly Joint Resolution No. 3 (81st Leg., 2021).",
        "implementation_url": "https://www.leg.state.nv.us/App/NELIS/REL/81st2021/Bill/7487/Overview",
    },
    {
        "state_id": "ME",
        "implementation_type": "Executive Commitment",
        "implementation_notes": "State climate action plan that includes Maine’s 30×30 conservation goal.",
        "implementation_citation": "State of Maine. (2020, December 1). Maine Won’t Wait: A Four‑Year Plan for Climate Action.",
        "implementation_url": "https://www.maine.gov/future/sites/maine.gov.future/files/inline-files/MaineWontWait_December2020.pdf",
    },
    {
        "state_id": "MA",
        "implementation_type": "Executive Commitment",
        "implementation_notes": "Executive order establishing biodiversity conservation framework aligned with 30×30 objectives.",
        "implementation_citation": "Commonwealth of Massachusetts. (2023, September 21). Executive Order No. 618: Biodiversity conservation in Massachusetts.",
        "implementation_url": "https://www.mass.gov/executive-orders/no-618-biodiversity-conservation-in-massachusetts",
    },
    {
        "state_id": "MD",
        "implementation_type": "Statute",
        "implementation_notes": "Statute codifying Maryland’s 30×30 conservation goal and implementation framework.",
        "implementation_citation": "State of Maryland. (2023). Senate Bill 470: Maryland the Beautiful Act (Ch. 546).",
        "implementation_url": "https://www.mgaleg.maryland.gov/2023RS/chapters_noln/Ch_546_sb0470E.pdf",
    },
    {
        "state_id": "MI",
        "implementation_type": "Executive Commitment",
        "implementation_notes": "Gov. Whitmer commits to freshwater conservation under the America the Beautiful Freshwater Challenge.",
        "implementation_citation": "State of Michigan, Office of the Governor. (2024, June 27). Gov. Whitmer accepts invitation to join White House initiative to conserve and restore freshwater resources: America the Beautiful Freshwater Challenge.",
        "implementation_url": "https://www.michigan.gov/whitmer/news/press-releases/2024/06/27/gov-whitmer-accepts-invitation-to-join-white-house-initiative",
    },
    {
        "state_id": "MI",
        "implementation_type": "Proposed Legislation",
        "implementation_notes": "Proposed statute to establish a 30×30 protection goal.",
        "implementation_citation": "Michigan Legislature. (2024). Senate Bill 1124.",
        "implementation_url": "https://www.legislature.mi.gov/Bills/Bill?ObjectName=2024‑SB‑1124",
    },
    {
        "state_id": "NJ",
        "implementation_type": "Executive Commitment",
        "implementation_notes": "Gov. Murphy joins the High Ambition Coalition for Nature and People (30×30 coalition).",
        "implementation_citation": "State of New Jersey, Office of the Governor. (2025, June 3). New Jersey joins Global Commitment to Preserve 30 % of Natural Lands by 2030.",
        "implementation_url": "https://www.nj.gov/governor/news/news/562025/approved/20250603c.shtml",
    },
    {
        "state_id": "NM",
        "implementation_type": "Executive Order",
        "implementation_notes": "Executive order establishing New Mexico’s 30×30 conservation framework.",
        "implementation_citation": "State of New Mexico. (2021, August 25). Executive Order 2021‑052: Protecting New Mexico’s Lands, Watersheds, Wildlife, and Natural Heritage.",
        "implementation_url": "https://www.governor.state.nm.us/wp-content/uploads/2021/08/Executive-Order-2021-052.pdf",
    },
    {
        "state_id": "NY",
        "implementation_type": "Statute",
        "implementation_notes": "Statute codifying New York’s 30×30 conservation goal.",
        "implementation_citation": "State of New York. (2022, December 23). Environmental Conservation Law § 49‑0113 — Thirty by thirty conservation goal.",
        "implementation_url": "https://www.nysenate.gov/legislation/laws/ENV/49‑0113",
    },
    {
        "state_id": "SC",
        "implementation_type": "Proposed Legislation",
        "implementation_notes": "Proposed statute to establish a 30×30 protection goal and corresponding interagency task force.",
        "implementation_citation": "South Carolina Legislature. (2020). S.1024: Environmental protection and conservation (123rd Leg.)",
        "implementation_url": "https://www.scstatehouse.gov/sess123_2019-2020/bills/1024.htm",
    },
    {
        "state_id": "SC",
        "implementation_type": "Proposed Legislation",
        "implementation_notes":  "Reintroduced conservation statute in the 124th General Assembly to establish 30x30 goal and interagency taskforce.",
        "implementation_citation": "South Carolina Legislature. (2021). S.220: SC Thirty‑by‑Thirty Conservation Act (124th Leg.)",
        "implementation_url": "https://www.scstatehouse.gov/sess124_2021-2022/bills/220.htm",
    },
    {
        "state_id": "VT",
        "implementation_type": "Statute",
        "implementation_notes": "Statute establishing Vermont’s 30×30 conservation goal and implementation framework.",
        "implementation_citation": "State of Vermont. (2023, June). Community Resilience and Biodiversity Protection Act (Act 59). Vermont General Assembly.",
        "implementation_url": "https://legislature.vermont.gov/Documents/2024/Docs/ACTS/ACT059/ACT059%20As%20Enacted.pdf",
    },
]

progress_sources = [
    {
        "state_id": "CA",
        "progress_type": "active",
        "progress_notes": "Annual report on state progress toward the 30×30 conservation goal.",
        "progress_citation": "California Natural Resources Agency. (2025). Pathways to 30×30 Annual Progress Report 2025.",
        "progress_url": "https://resources.ca.gov/-/media/CNRA-Website/Files/2025-30x30-Pathways-Progress-Report.pdf",
    },
    {
        "state_id": "HI",
        "progress_type": "halted",
        "progress_notes": "DLNR document describing reframing of the initiative and dropping the explicit 30×30 target language.",
        "progress_citation": "Hawaiʻi Department of Land and Natural Resources, Division of Aquatic Resources. (2024, July). Holomua Marine Initiative: A guide to navigating nearshore resource management.",
        "progress_url": "https://dlnr.hawaii.gov/holomua/files/2024/07/Holomua-Guide-Final-July2024.pdf",
    },
    {
        "state_id": "IL",
        "progress_type": "active",
        "progress_notes": "Illinois DNR program page describing the state’s 30 by 30 work and coordinating activities.",
        "progress_citation": "Illinois Department of Natural Resources. (n.d.). Illinois 30 by 30 Conservation Task Force.",
        "progress_url": "https://dnr.illinois.gov/programs/30by30.html",
    },
    {
        "state_id": "NV",
        "progress_type": "active",
        "progress_notes": "",
        "progress_citation": "",
        "progress_url": "",
    },
    {
        "state_id": "ME",
        "progress_type": "active",
        "progress_notes": "",
        "progress_citation": "",
        "progress_url": "",
    },
    {
        "state_id": "MA",
        "progress_type": "active",
        "progress_notes": "Commonwealth page describing biodiversity conservation goals and implementation context (post-EO 618).",
        "progress_citation": "Commonwealth of Massachusetts. (2025). Biodiversity Goals for Massachusetts.",
        "progress_url": "https://www.mass.gov/info-details/biodiversity-goals-for-massachusetts",
    },
    {
        "state_id": "MD",
        "progress_type": "achieved",
        "progress_notes": "State announcement reporting Maryland has met the 30% protected lands milestone ahead of schedule.",
        "progress_citation": "Maryland Department of Natural Resources. (2024, May 15). Governor Moore Announces Maryland Meets 30% of State Land Conservation Goal Six Years Ahead of Schedule.",
        "progress_url": "https://news.maryland.gov/dnr/2024/05/15/governor-moore-announces-maryland-meets-30-of-state-land-conservation-goal-six-years-ahead-of-schedule/",
    },
    {
        "state_id": "MI",
        "progress_type": "active",
        "progress_notes": "",
        "progress_citation": "",
        "progress_url": "",
    },
    {
        "state_id": "NJ",
        "progress_type": "achieved",
        "progress_notes": "State press release includes statement that New Jersey has already achieved the 30×30 goal.",
        "progress_citation": "State of New Jersey, Office of the Governor. (2025, June 3). New Jersey joins Global Commitment to Preserve 30% of Natural Lands by 2030.",
        "progress_url": "https://www.nj.gov/governor/news/news/562025/approved/20250603c.shtml",
    },
    {
        "state_id": "NM",
        "progress_type": "achieved",
        "progress_notes": "Official 30×30 annual report identifies over 25 million acres meeting the state committee’s definition of conserved lands (which is over 30% of NM's area) but does not explicitly declare that New Mexico has achieved the 30×30 goal.",
        "progress_citation": "New Mexico Energy, Minerals and Natural Resources Department, Forestry Division. (2024). 30 × 30 New Mexico: 2024 Annual Report.",
        "progress_url": "https://www.emnrd.nm.gov/sfd/wp-content/uploads/sites/4/30x30-2024-Annual-Report-Final.pdf",
    },
    {
        "state_id": "NY",
        "progress_type": "active",
        "progress_notes": "",
        "progress_citation": "",
        "progress_url": "",
    },
    {
        "state_id": "SC",
        "progress_type": "failed_legislation",
        "progress_notes": "Introduced legislation related to 30×30; Did not pass",
        "progress_citation": "South Carolina Legislature. (2020). S.1024: Environmental protection and conservation (123rd Leg.).",
        "progress_url": "https://www.scstatehouse.gov/sess123_2019-2020/bills/1024.htm",
    },
    {
        "state_id": "SC",
        "progress_type": "failed_legislation",
        "progress_notes": "Reintroduced legislation related to 30×30; Did not pass",
        "progress_citation": "South Carolina Legislature. (2021). S.220: SC Thirty‑by‑Thirty Conservation Act (124th Leg.)",
        "progress_url": "https://www.scstatehouse.gov/sess124_2021-2022/bills/220.htm",
    },
    {
        "state_id": "VT",
        "progress_type": "active",
        "progress_notes": "",
        "progress_citation": "",
        "progress_url": "",
    },
]

